# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: assets.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='assets.proto',
  package='gameMsg',
  syntax='proto2',
  serialized_pb=_b('\n\x0c\x61ssets.proto\x12\x07gameMsg\"N\n\x0b\x41ssetUpdate\x12\x0f\n\x07nUserID\x18\x01 \x02(\t\x12\r\n\x05nGold\x18\x02 \x01(\x05\x12\x0e\n\x06nMoney\x18\x03 \x01(\x05\x12\x0f\n\x07sAssets\x18\x04 \x01(\t')
)




_ASSETUPDATE = _descriptor.Descriptor(
  name='AssetUpdate',
  full_name='gameMsg.AssetUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='gameMsg.AssetUpdate.nUserID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nGold', full_name='gameMsg.AssetUpdate.nGold', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nMoney', full_name='gameMsg.AssetUpdate.nMoney', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sAssets', full_name='gameMsg.AssetUpdate.sAssets', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['AssetUpdate'] = _ASSETUPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AssetUpdate = _reflection.GeneratedProtocolMessageType('AssetUpdate', (_message.Message,), dict(
  DESCRIPTOR = _ASSETUPDATE,
  __module__ = 'assets_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.AssetUpdate)
  ))
_sym_db.RegisterMessage(AssetUpdate)


# @@protoc_insertion_point(module_scope)
