# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import assets_pb2 as assets__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='buy.proto',
  package='gameMsg',
  syntax='proto2',
  serialized_pb=_b('\n\tbuy.proto\x12\x07gameMsg\x1a\x0c\x61ssets.proto\"#\n\x04Good\x12\x0b\n\x03nID\x18\x01 \x02(\x05\x12\x0e\n\x06nCount\x18\x02 \x02(\x05\";\n\nBuyRequest\x12\x0f\n\x07nUserID\x18\x01 \x02(\t\x12\x1c\n\x05goods\x18\x02 \x03(\x0b\x32\r.gameMsg.Good\"6\n\x0b\x42uyResponse\x12\'\n\tnewAssets\x18\x01 \x01(\x0b\x32\x14.gameMsg.AssetUpdate')
  ,
  dependencies=[assets__pb2.DESCRIPTOR,])




_GOOD = _descriptor.Descriptor(
  name='Good',
  full_name='gameMsg.Good',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nID', full_name='gameMsg.Good.nID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nCount', full_name='gameMsg.Good.nCount', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=71,
)


_BUYREQUEST = _descriptor.Descriptor(
  name='BuyRequest',
  full_name='gameMsg.BuyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='gameMsg.BuyRequest.nUserID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='goods', full_name='gameMsg.BuyRequest.goods', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=132,
)


_BUYRESPONSE = _descriptor.Descriptor(
  name='BuyResponse',
  full_name='gameMsg.BuyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='newAssets', full_name='gameMsg.BuyResponse.newAssets', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=188,
)

_BUYREQUEST.fields_by_name['goods'].message_type = _GOOD
_BUYRESPONSE.fields_by_name['newAssets'].message_type = assets__pb2._ASSETUPDATE
DESCRIPTOR.message_types_by_name['Good'] = _GOOD
DESCRIPTOR.message_types_by_name['BuyRequest'] = _BUYREQUEST
DESCRIPTOR.message_types_by_name['BuyResponse'] = _BUYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Good = _reflection.GeneratedProtocolMessageType('Good', (_message.Message,), dict(
  DESCRIPTOR = _GOOD,
  __module__ = 'buy_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.Good)
  ))
_sym_db.RegisterMessage(Good)

BuyRequest = _reflection.GeneratedProtocolMessageType('BuyRequest', (_message.Message,), dict(
  DESCRIPTOR = _BUYREQUEST,
  __module__ = 'buy_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.BuyRequest)
  ))
_sym_db.RegisterMessage(BuyRequest)

BuyResponse = _reflection.GeneratedProtocolMessageType('BuyResponse', (_message.Message,), dict(
  DESCRIPTOR = _BUYRESPONSE,
  __module__ = 'buy_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.BuyResponse)
  ))
_sym_db.RegisterMessage(BuyResponse)


# @@protoc_insertion_point(module_scope)
