# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: create_room.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='create_room.proto',
  package='gameMsg',
  syntax='proto2',
  serialized_pb=_b('\n\x11\x63reate_room.proto\x12\x07gameMsg\" \n\x11\x43reateRoomRequest\x12\x0b\n\x03sID\x18\x01 \x02(\t\"%\n\x12\x43reateRoomResponse\x12\x0f\n\x07sRoomID\x18\x01 \x02(\t')
)




_CREATEROOMREQUEST = _descriptor.Descriptor(
  name='CreateRoomRequest',
  full_name='gameMsg.CreateRoomRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sID', full_name='gameMsg.CreateRoomRequest.sID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=62,
)


_CREATEROOMRESPONSE = _descriptor.Descriptor(
  name='CreateRoomResponse',
  full_name='gameMsg.CreateRoomResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='gameMsg.CreateRoomResponse.sRoomID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=101,
)

DESCRIPTOR.message_types_by_name['CreateRoomRequest'] = _CREATEROOMREQUEST
DESCRIPTOR.message_types_by_name['CreateRoomResponse'] = _CREATEROOMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateRoomRequest = _reflection.GeneratedProtocolMessageType('CreateRoomRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEROOMREQUEST,
  __module__ = 'create_room_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.CreateRoomRequest)
  ))
_sym_db.RegisterMessage(CreateRoomRequest)

CreateRoomResponse = _reflection.GeneratedProtocolMessageType('CreateRoomResponse', (_message.Message,), dict(
  DESCRIPTOR = _CREATEROOMRESPONSE,
  __module__ = 'create_room_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.CreateRoomResponse)
  ))
_sym_db.RegisterMessage(CreateRoomResponse)


# @@protoc_insertion_point(module_scope)
