# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: end_game.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='end_game.proto',
  package='gameMsg',
  syntax='proto2',
  serialized_pb=_b('\n\x0e\x65nd_game.proto\x12\x07gameMsg\"`\n\x0fRankEndGameData\x12\x10\n\x08sGamerID\x18\x01 \x02(\t\x12\r\n\x05nRank\x18\x02 \x02(\x05\x12\r\n\x05nTime\x18\x03 \x02(\x05\x12\r\n\x05nGold\x18\x04 \x02(\x05\x12\x0e\n\x06nLevel\x18\x05 \x02(\x05\".\n\x0e\x45ndGameRequest\x12\x0b\n\x03sID\x18\x01 \x02(\t\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\"2\n\x0f\x45ndGameResponse\x12\x10\n\x08sGamerID\x18\x01 \x02(\t\x12\r\n\x05nRank\x18\x02 \x02(\x05\"T\n\rEndGameNotify\x12\x0f\n\x07sRoomID\x18\x01 \x02(\t\x12\x32\n\x10rankEndGameDatas\x18\x02 \x03(\x0b\x32\x18.gameMsg.RankEndGameData\"1\n\x0eOverTimeNotify\x12\x10\n\x08sGamerID\x18\x01 \x02(\t\x12\r\n\x05nRank\x18\x02 \x02(\x05')
)




_RANKENDGAMEDATA = _descriptor.Descriptor(
  name='RankEndGameData',
  full_name='gameMsg.RankEndGameData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sGamerID', full_name='gameMsg.RankEndGameData.sGamerID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nRank', full_name='gameMsg.RankEndGameData.nRank', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nTime', full_name='gameMsg.RankEndGameData.nTime', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nGold', full_name='gameMsg.RankEndGameData.nGold', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nLevel', full_name='gameMsg.RankEndGameData.nLevel', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=123,
)


_ENDGAMEREQUEST = _descriptor.Descriptor(
  name='EndGameRequest',
  full_name='gameMsg.EndGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sID', full_name='gameMsg.EndGameRequest.sID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='gameMsg.EndGameRequest.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=171,
)


_ENDGAMERESPONSE = _descriptor.Descriptor(
  name='EndGameResponse',
  full_name='gameMsg.EndGameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sGamerID', full_name='gameMsg.EndGameResponse.sGamerID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nRank', full_name='gameMsg.EndGameResponse.nRank', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=223,
)


_ENDGAMENOTIFY = _descriptor.Descriptor(
  name='EndGameNotify',
  full_name='gameMsg.EndGameNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='gameMsg.EndGameNotify.sRoomID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rankEndGameDatas', full_name='gameMsg.EndGameNotify.rankEndGameDatas', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=309,
)


_OVERTIMENOTIFY = _descriptor.Descriptor(
  name='OverTimeNotify',
  full_name='gameMsg.OverTimeNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sGamerID', full_name='gameMsg.OverTimeNotify.sGamerID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nRank', full_name='gameMsg.OverTimeNotify.nRank', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=360,
)

_ENDGAMENOTIFY.fields_by_name['rankEndGameDatas'].message_type = _RANKENDGAMEDATA
DESCRIPTOR.message_types_by_name['RankEndGameData'] = _RANKENDGAMEDATA
DESCRIPTOR.message_types_by_name['EndGameRequest'] = _ENDGAMEREQUEST
DESCRIPTOR.message_types_by_name['EndGameResponse'] = _ENDGAMERESPONSE
DESCRIPTOR.message_types_by_name['EndGameNotify'] = _ENDGAMENOTIFY
DESCRIPTOR.message_types_by_name['OverTimeNotify'] = _OVERTIMENOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RankEndGameData = _reflection.GeneratedProtocolMessageType('RankEndGameData', (_message.Message,), dict(
  DESCRIPTOR = _RANKENDGAMEDATA,
  __module__ = 'end_game_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.RankEndGameData)
  ))
_sym_db.RegisterMessage(RankEndGameData)

EndGameRequest = _reflection.GeneratedProtocolMessageType('EndGameRequest', (_message.Message,), dict(
  DESCRIPTOR = _ENDGAMEREQUEST,
  __module__ = 'end_game_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.EndGameRequest)
  ))
_sym_db.RegisterMessage(EndGameRequest)

EndGameResponse = _reflection.GeneratedProtocolMessageType('EndGameResponse', (_message.Message,), dict(
  DESCRIPTOR = _ENDGAMERESPONSE,
  __module__ = 'end_game_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.EndGameResponse)
  ))
_sym_db.RegisterMessage(EndGameResponse)

EndGameNotify = _reflection.GeneratedProtocolMessageType('EndGameNotify', (_message.Message,), dict(
  DESCRIPTOR = _ENDGAMENOTIFY,
  __module__ = 'end_game_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.EndGameNotify)
  ))
_sym_db.RegisterMessage(EndGameNotify)

OverTimeNotify = _reflection.GeneratedProtocolMessageType('OverTimeNotify', (_message.Message,), dict(
  DESCRIPTOR = _OVERTIMENOTIFY,
  __module__ = 'end_game_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.OverTimeNotify)
  ))
_sym_db.RegisterMessage(OverTimeNotify)


# @@protoc_insertion_point(module_scope)
