# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: errorcode.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='errorcode.proto',
  package='gameMsg',
  syntax='proto2',
  serialized_pb=_b('\n\x0f\x65rrorcode.proto\x12\x07gameMsg*u\n\tErrorCode\x12\x0b\n\x07success\x10\x01\x12\x0f\n\x0buserinvaild\x10\x02\x12\x0c\n\x08pwderror\x10\x03\x12\x0e\n\nmoneyerror\x10\x04\x12\x0e\n\ngateunlock\x10\x05\x12\x0e\n\nptomptnone\x10\x06\x12\x0c\n\x08maxgates\x10\x07')
)

_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='gameMsg.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='success', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='userinvaild', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='pwderror', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='moneyerror', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='gateunlock', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ptomptnone', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='maxgates', index=6, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=28,
  serialized_end=145,
)
_sym_db.RegisterEnumDescriptor(_ERRORCODE)

ErrorCode = enum_type_wrapper.EnumTypeWrapper(_ERRORCODE)
success = 1
userinvaild = 2
pwderror = 3
moneyerror = 4
gateunlock = 5
ptomptnone = 6
maxgates = 7


DESCRIPTOR.enum_types_by_name['ErrorCode'] = _ERRORCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
