# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: join_room.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='join_room.proto',
  package='gameMsg',
  syntax='proto2',
  serialized_pb=_b('\n\x0fjoin_room.proto\x12\x07gameMsg\"I\n\x05Gamer\x12\x0b\n\x03sID\x18\x01 \x02(\t\x12\x10\n\x08sHeadImg\x18\x02 \x01(\t\x12\r\n\x05sNick\x18\x03 \x01(\t\x12\x12\n\nnRankLevel\x18\x04 \x01(\x05\"H\n\x04Room\x12\x1e\n\x06gamers\x18\x01 \x03(\x0b\x32\x0e.gameMsg.Gamer\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\x12\x0f\n\x07sBossID\x18\x03 \x02(\t\"/\n\x0fJoinRoomRequest\x12\x0b\n\x03sID\x18\x01 \x02(\t\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\"3\n\x10JoinRoomResponse\x12\x1f\n\x08joinRoom\x18\x01 \x02(\x0b\x32\r.gameMsg.Room\"3\n\x0eJoinRoomNotify\x12!\n\tjoinGamer\x18\x01 \x02(\x0b\x32\x0e.gameMsg.Gamer')
)




_GAMER = _descriptor.Descriptor(
  name='Gamer',
  full_name='gameMsg.Gamer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sID', full_name='gameMsg.Gamer.sID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sHeadImg', full_name='gameMsg.Gamer.sHeadImg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sNick', full_name='gameMsg.Gamer.sNick', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nRankLevel', full_name='gameMsg.Gamer.nRankLevel', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=101,
)


_ROOM = _descriptor.Descriptor(
  name='Room',
  full_name='gameMsg.Room',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gamers', full_name='gameMsg.Room.gamers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='gameMsg.Room.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sBossID', full_name='gameMsg.Room.sBossID', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=175,
)


_JOINROOMREQUEST = _descriptor.Descriptor(
  name='JoinRoomRequest',
  full_name='gameMsg.JoinRoomRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sID', full_name='gameMsg.JoinRoomRequest.sID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='gameMsg.JoinRoomRequest.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=224,
)


_JOINROOMRESPONSE = _descriptor.Descriptor(
  name='JoinRoomResponse',
  full_name='gameMsg.JoinRoomResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='joinRoom', full_name='gameMsg.JoinRoomResponse.joinRoom', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=277,
)


_JOINROOMNOTIFY = _descriptor.Descriptor(
  name='JoinRoomNotify',
  full_name='gameMsg.JoinRoomNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='joinGamer', full_name='gameMsg.JoinRoomNotify.joinGamer', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=330,
)

_ROOM.fields_by_name['gamers'].message_type = _GAMER
_JOINROOMRESPONSE.fields_by_name['joinRoom'].message_type = _ROOM
_JOINROOMNOTIFY.fields_by_name['joinGamer'].message_type = _GAMER
DESCRIPTOR.message_types_by_name['Gamer'] = _GAMER
DESCRIPTOR.message_types_by_name['Room'] = _ROOM
DESCRIPTOR.message_types_by_name['JoinRoomRequest'] = _JOINROOMREQUEST
DESCRIPTOR.message_types_by_name['JoinRoomResponse'] = _JOINROOMRESPONSE
DESCRIPTOR.message_types_by_name['JoinRoomNotify'] = _JOINROOMNOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Gamer = _reflection.GeneratedProtocolMessageType('Gamer', (_message.Message,), dict(
  DESCRIPTOR = _GAMER,
  __module__ = 'join_room_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.Gamer)
  ))
_sym_db.RegisterMessage(Gamer)

Room = _reflection.GeneratedProtocolMessageType('Room', (_message.Message,), dict(
  DESCRIPTOR = _ROOM,
  __module__ = 'join_room_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.Room)
  ))
_sym_db.RegisterMessage(Room)

JoinRoomRequest = _reflection.GeneratedProtocolMessageType('JoinRoomRequest', (_message.Message,), dict(
  DESCRIPTOR = _JOINROOMREQUEST,
  __module__ = 'join_room_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.JoinRoomRequest)
  ))
_sym_db.RegisterMessage(JoinRoomRequest)

JoinRoomResponse = _reflection.GeneratedProtocolMessageType('JoinRoomResponse', (_message.Message,), dict(
  DESCRIPTOR = _JOINROOMRESPONSE,
  __module__ = 'join_room_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.JoinRoomResponse)
  ))
_sym_db.RegisterMessage(JoinRoomResponse)

JoinRoomNotify = _reflection.GeneratedProtocolMessageType('JoinRoomNotify', (_message.Message,), dict(
  DESCRIPTOR = _JOINROOMNOTIFY,
  __module__ = 'join_room_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.JoinRoomNotify)
  ))
_sym_db.RegisterMessage(JoinRoomNotify)


# @@protoc_insertion_point(module_scope)
