# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='login.proto',
  package='gameMsg',
  syntax='proto2',
  serialized_pb=_b('\n\x0blogin.proto\x12\x07gameMsg\"~\n\x04User\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\r\n\x05nGold\x18\x02 \x01(\x05\x12\x13\n\x0bnSeeAdTimes\x18\x03 \x01(\x05\x12\x13\n\x0bnShareTimes\x18\x04 \x01(\x05\x12\x15\n\rnGetTipsTimes\x18\x05 \x01(\x05\x12\x15\n\rnPopaddsTimes\x18\x06 \x01(\x05\"#\n\x04Gate\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0f\n\x07starNum\x18\x02 \x02(\x05\"\x81\x01\n\x0cLoginRequest\x12\x0b\n\x03sID\x18\x01 \x02(\t\x12\r\n\x05sNick\x18\x02 \x01(\t\x12\x10\n\x08sHeadimg\x18\x03 \x01(\t\x12\r\n\x05sCity\x18\x04 \x01(\t\x12\x0f\n\x07nGender\x18\x05 \x01(\x05\x12\x11\n\tsProvince\x18\x06 \x01(\t\x12\x10\n\x08sCountry\x18\x07 \x01(\t\"d\n\rLoginResponse\x12 \n\trequester\x18\x01 \x02(\x0b\x32\r.gameMsg.User\x12\x1c\n\x05gates\x18\x02 \x03(\x0b\x32\r.gameMsg.Gate\x12\x13\n\x0bnServerTime\x18\x03 \x02(\x05')
)




_USER = _descriptor.Descriptor(
  name='User',
  full_name='gameMsg.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='gameMsg.User.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nGold', full_name='gameMsg.User.nGold', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nSeeAdTimes', full_name='gameMsg.User.nSeeAdTimes', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nShareTimes', full_name='gameMsg.User.nShareTimes', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nGetTipsTimes', full_name='gameMsg.User.nGetTipsTimes', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nPopaddsTimes', full_name='gameMsg.User.nPopaddsTimes', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=150,
)


_GATE = _descriptor.Descriptor(
  name='Gate',
  full_name='gameMsg.Gate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='gameMsg.Gate.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='starNum', full_name='gameMsg.Gate.starNum', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=187,
)


_LOGINREQUEST = _descriptor.Descriptor(
  name='LoginRequest',
  full_name='gameMsg.LoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sID', full_name='gameMsg.LoginRequest.sID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sNick', full_name='gameMsg.LoginRequest.sNick', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sHeadimg', full_name='gameMsg.LoginRequest.sHeadimg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sCity', full_name='gameMsg.LoginRequest.sCity', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nGender', full_name='gameMsg.LoginRequest.nGender', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sProvince', full_name='gameMsg.LoginRequest.sProvince', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sCountry', full_name='gameMsg.LoginRequest.sCountry', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=319,
)


_LOGINRESPONSE = _descriptor.Descriptor(
  name='LoginResponse',
  full_name='gameMsg.LoginResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requester', full_name='gameMsg.LoginResponse.requester', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gates', full_name='gameMsg.LoginResponse.gates', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nServerTime', full_name='gameMsg.LoginResponse.nServerTime', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=421,
)

_LOGINRESPONSE.fields_by_name['requester'].message_type = _USER
_LOGINRESPONSE.fields_by_name['gates'].message_type = _GATE
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['Gate'] = _GATE
DESCRIPTOR.message_types_by_name['LoginRequest'] = _LOGINREQUEST
DESCRIPTOR.message_types_by_name['LoginResponse'] = _LOGINRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.User)
  ))
_sym_db.RegisterMessage(User)

Gate = _reflection.GeneratedProtocolMessageType('Gate', (_message.Message,), dict(
  DESCRIPTOR = _GATE,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.Gate)
  ))
_sym_db.RegisterMessage(Gate)

LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOGINREQUEST,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.LoginRequest)
  ))
_sym_db.RegisterMessage(LoginRequest)

LoginResponse = _reflection.GeneratedProtocolMessageType('LoginResponse', (_message.Message,), dict(
  DESCRIPTOR = _LOGINRESPONSE,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.LoginResponse)
  ))
_sym_db.RegisterMessage(LoginResponse)


# @@protoc_insertion_point(module_scope)
