# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: play_begin.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='play_begin.proto',
  package='gameMsg',
  syntax='proto2',
  serialized_pb=_b('\n\x10play_begin.proto\x12\x07gameMsg\"/\n\x10PlayBeginRequest\x12\x0b\n\x03sID\x18\x01 \x02(\t\x12\x0e\n\x06gateID\x18\x02 \x02(\x05\"F\n\x11PlayBeginResponse\x12\x0e\n\x06gateId\x18\x01 \x02(\x05\x12\x10\n\x08nTopStar\x18\x02 \x01(\x05\x12\x0f\n\x07nPrompt\x18\x03 \x01(\x05')
)




_PLAYBEGINREQUEST = _descriptor.Descriptor(
  name='PlayBeginRequest',
  full_name='gameMsg.PlayBeginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sID', full_name='gameMsg.PlayBeginRequest.sID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gateID', full_name='gameMsg.PlayBeginRequest.gateID', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=76,
)


_PLAYBEGINRESPONSE = _descriptor.Descriptor(
  name='PlayBeginResponse',
  full_name='gameMsg.PlayBeginResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gateId', full_name='gameMsg.PlayBeginResponse.gateId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nTopStar', full_name='gameMsg.PlayBeginResponse.nTopStar', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nPrompt', full_name='gameMsg.PlayBeginResponse.nPrompt', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=148,
)

DESCRIPTOR.message_types_by_name['PlayBeginRequest'] = _PLAYBEGINREQUEST
DESCRIPTOR.message_types_by_name['PlayBeginResponse'] = _PLAYBEGINRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayBeginRequest = _reflection.GeneratedProtocolMessageType('PlayBeginRequest', (_message.Message,), dict(
  DESCRIPTOR = _PLAYBEGINREQUEST,
  __module__ = 'play_begin_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.PlayBeginRequest)
  ))
_sym_db.RegisterMessage(PlayBeginRequest)

PlayBeginResponse = _reflection.GeneratedProtocolMessageType('PlayBeginResponse', (_message.Message,), dict(
  DESCRIPTOR = _PLAYBEGINRESPONSE,
  __module__ = 'play_begin_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.PlayBeginResponse)
  ))
_sym_db.RegisterMessage(PlayBeginResponse)


# @@protoc_insertion_point(module_scope)
