# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: play_end.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import login_pb2 as login__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='play_end.proto',
  package='gameMsg',
  syntax='proto2',
  serialized_pb=_b('\n\x0eplay_end.proto\x12\x07gameMsg\x1a\x0blogin.proto\"-\n\x0ePlayEndRequest\x12\x0b\n\x03sID\x18\x01 \x02(\t\x12\x0e\n\x06gateID\x18\x02 \x02(\x05\"r\n\x0fPlayEndResponse\x12\x0e\n\x06gateID\x18\x01 \x02(\x05\x12\x10\n\x08nTopStar\x18\x02 \x01(\x05\x12\x10\n\x08nGetGold\x18\x03 \x01(\x05\x12\r\n\x05nGold\x18\x04 \x01(\x05\x12\x1c\n\x05gates\x18\x05 \x03(\x0b\x32\r.gameMsg.Gate')
  ,
  dependencies=[login__pb2.DESCRIPTOR,])




_PLAYENDREQUEST = _descriptor.Descriptor(
  name='PlayEndRequest',
  full_name='gameMsg.PlayEndRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sID', full_name='gameMsg.PlayEndRequest.sID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gateID', full_name='gameMsg.PlayEndRequest.gateID', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=85,
)


_PLAYENDRESPONSE = _descriptor.Descriptor(
  name='PlayEndResponse',
  full_name='gameMsg.PlayEndResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gateID', full_name='gameMsg.PlayEndResponse.gateID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nTopStar', full_name='gameMsg.PlayEndResponse.nTopStar', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nGetGold', full_name='gameMsg.PlayEndResponse.nGetGold', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nGold', full_name='gameMsg.PlayEndResponse.nGold', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gates', full_name='gameMsg.PlayEndResponse.gates', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=201,
)

_PLAYENDRESPONSE.fields_by_name['gates'].message_type = login__pb2._GATE
DESCRIPTOR.message_types_by_name['PlayEndRequest'] = _PLAYENDREQUEST
DESCRIPTOR.message_types_by_name['PlayEndResponse'] = _PLAYENDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayEndRequest = _reflection.GeneratedProtocolMessageType('PlayEndRequest', (_message.Message,), dict(
  DESCRIPTOR = _PLAYENDREQUEST,
  __module__ = 'play_end_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.PlayEndRequest)
  ))
_sym_db.RegisterMessage(PlayEndRequest)

PlayEndResponse = _reflection.GeneratedProtocolMessageType('PlayEndResponse', (_message.Message,), dict(
  DESCRIPTOR = _PLAYENDRESPONSE,
  __module__ = 'play_end_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.PlayEndResponse)
  ))
_sym_db.RegisterMessage(PlayEndResponse)


# @@protoc_insertion_point(module_scope)
