# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: play_block.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='play_block.proto',
  package='gameMsg',
  syntax='proto2',
  serialized_pb=_b('\n\x10play_block.proto\x12\x07gameMsg\"C\n\x13PlayBlockAddRequest\x12\x0b\n\x03sID\x18\x01 \x02(\t\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\x12\x0e\n\x06gateID\x18\x03 \x02(\x05\"\x16\n\x14PlayBlockAddResponse\"F\n\x16PlayBlockDeleteRequest\x12\x0b\n\x03sID\x18\x01 \x02(\t\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\x12\x0e\n\x06gateID\x18\x03 \x02(\x05\"\x19\n\x17PlayBlockDeleteResponse\"N\n\x0fPlayBlockNotify\x12\x0b\n\x03sID\x18\x01 \x02(\t\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\x12\x0e\n\x06gateID\x18\x03 \x02(\x05\x12\r\n\x05isAdd\x18\x04 \x02(\x08')
)




_PLAYBLOCKADDREQUEST = _descriptor.Descriptor(
  name='PlayBlockAddRequest',
  full_name='gameMsg.PlayBlockAddRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sID', full_name='gameMsg.PlayBlockAddRequest.sID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='gameMsg.PlayBlockAddRequest.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gateID', full_name='gameMsg.PlayBlockAddRequest.gateID', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=96,
)


_PLAYBLOCKADDRESPONSE = _descriptor.Descriptor(
  name='PlayBlockAddResponse',
  full_name='gameMsg.PlayBlockAddResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=120,
)


_PLAYBLOCKDELETEREQUEST = _descriptor.Descriptor(
  name='PlayBlockDeleteRequest',
  full_name='gameMsg.PlayBlockDeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sID', full_name='gameMsg.PlayBlockDeleteRequest.sID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='gameMsg.PlayBlockDeleteRequest.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gateID', full_name='gameMsg.PlayBlockDeleteRequest.gateID', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=192,
)


_PLAYBLOCKDELETERESPONSE = _descriptor.Descriptor(
  name='PlayBlockDeleteResponse',
  full_name='gameMsg.PlayBlockDeleteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=219,
)


_PLAYBLOCKNOTIFY = _descriptor.Descriptor(
  name='PlayBlockNotify',
  full_name='gameMsg.PlayBlockNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sID', full_name='gameMsg.PlayBlockNotify.sID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='gameMsg.PlayBlockNotify.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gateID', full_name='gameMsg.PlayBlockNotify.gateID', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isAdd', full_name='gameMsg.PlayBlockNotify.isAdd', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=299,
)

DESCRIPTOR.message_types_by_name['PlayBlockAddRequest'] = _PLAYBLOCKADDREQUEST
DESCRIPTOR.message_types_by_name['PlayBlockAddResponse'] = _PLAYBLOCKADDRESPONSE
DESCRIPTOR.message_types_by_name['PlayBlockDeleteRequest'] = _PLAYBLOCKDELETEREQUEST
DESCRIPTOR.message_types_by_name['PlayBlockDeleteResponse'] = _PLAYBLOCKDELETERESPONSE
DESCRIPTOR.message_types_by_name['PlayBlockNotify'] = _PLAYBLOCKNOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayBlockAddRequest = _reflection.GeneratedProtocolMessageType('PlayBlockAddRequest', (_message.Message,), dict(
  DESCRIPTOR = _PLAYBLOCKADDREQUEST,
  __module__ = 'play_block_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.PlayBlockAddRequest)
  ))
_sym_db.RegisterMessage(PlayBlockAddRequest)

PlayBlockAddResponse = _reflection.GeneratedProtocolMessageType('PlayBlockAddResponse', (_message.Message,), dict(
  DESCRIPTOR = _PLAYBLOCKADDRESPONSE,
  __module__ = 'play_block_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.PlayBlockAddResponse)
  ))
_sym_db.RegisterMessage(PlayBlockAddResponse)

PlayBlockDeleteRequest = _reflection.GeneratedProtocolMessageType('PlayBlockDeleteRequest', (_message.Message,), dict(
  DESCRIPTOR = _PLAYBLOCKDELETEREQUEST,
  __module__ = 'play_block_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.PlayBlockDeleteRequest)
  ))
_sym_db.RegisterMessage(PlayBlockDeleteRequest)

PlayBlockDeleteResponse = _reflection.GeneratedProtocolMessageType('PlayBlockDeleteResponse', (_message.Message,), dict(
  DESCRIPTOR = _PLAYBLOCKDELETERESPONSE,
  __module__ = 'play_block_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.PlayBlockDeleteResponse)
  ))
_sym_db.RegisterMessage(PlayBlockDeleteResponse)

PlayBlockNotify = _reflection.GeneratedProtocolMessageType('PlayBlockNotify', (_message.Message,), dict(
  DESCRIPTOR = _PLAYBLOCKNOTIFY,
  __module__ = 'play_block_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.PlayBlockNotify)
  ))
_sym_db.RegisterMessage(PlayBlockNotify)


# @@protoc_insertion_point(module_scope)
