# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rank.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rank.proto',
  package='gameMsg',
  syntax='proto2',
  serialized_pb=_b('\n\nrank.proto\x12\x07gameMsg\"W\n\x08RankData\x12\n\n\x02id\x18\x01 \x02(\x05\x12\r\n\x05sNick\x18\x02 \x02(\t\x12\r\n\x05nRank\x18\x03 \x02(\x05\x12\x0f\n\x07starNum\x18\x04 \x02(\x05\x12\x10\n\x08sHeadimg\x18\x05 \x02(\t\"\x1a\n\x0bRankRequest\x12\x0b\n\x03sID\x18\x01 \x02(\t\"4\n\x0cRankResponse\x12$\n\trankDatas\x18\x01 \x03(\x0b\x32\x11.gameMsg.RankData')
)




_RANKDATA = _descriptor.Descriptor(
  name='RankData',
  full_name='gameMsg.RankData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='gameMsg.RankData.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sNick', full_name='gameMsg.RankData.sNick', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nRank', full_name='gameMsg.RankData.nRank', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='starNum', full_name='gameMsg.RankData.starNum', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sHeadimg', full_name='gameMsg.RankData.sHeadimg', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=110,
)


_RANKREQUEST = _descriptor.Descriptor(
  name='RankRequest',
  full_name='gameMsg.RankRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sID', full_name='gameMsg.RankRequest.sID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=138,
)


_RANKRESPONSE = _descriptor.Descriptor(
  name='RankResponse',
  full_name='gameMsg.RankResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rankDatas', full_name='gameMsg.RankResponse.rankDatas', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=192,
)

_RANKRESPONSE.fields_by_name['rankDatas'].message_type = _RANKDATA
DESCRIPTOR.message_types_by_name['RankData'] = _RANKDATA
DESCRIPTOR.message_types_by_name['RankRequest'] = _RANKREQUEST
DESCRIPTOR.message_types_by_name['RankResponse'] = _RANKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RankData = _reflection.GeneratedProtocolMessageType('RankData', (_message.Message,), dict(
  DESCRIPTOR = _RANKDATA,
  __module__ = 'rank_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.RankData)
  ))
_sym_db.RegisterMessage(RankData)

RankRequest = _reflection.GeneratedProtocolMessageType('RankRequest', (_message.Message,), dict(
  DESCRIPTOR = _RANKREQUEST,
  __module__ = 'rank_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.RankRequest)
  ))
_sym_db.RegisterMessage(RankRequest)

RankResponse = _reflection.GeneratedProtocolMessageType('RankResponse', (_message.Message,), dict(
  DESCRIPTOR = _RANKRESPONSE,
  __module__ = 'rank_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.RankResponse)
  ))
_sym_db.RegisterMessage(RankResponse)


# @@protoc_insertion_point(module_scope)
