# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: see_ad.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='see_ad.proto',
  package='gameMsg',
  syntax='proto2',
  serialized_pb=_b('\n\x0csee_ad.proto\x12\x07gameMsg\")\n\x0cSeeAdRequest\x12\x0b\n\x03sID\x18\x01 \x02(\t\x12\x0c\n\x04\x61\x64ID\x18\x02 \x02(\x05\" \n\rSeeAdResponse\x12\x0f\n\x07nPrompt\x18\x01 \x01(\x05')
)




_SEEADREQUEST = _descriptor.Descriptor(
  name='SeeAdRequest',
  full_name='gameMsg.SeeAdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sID', full_name='gameMsg.SeeAdRequest.sID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='adID', full_name='gameMsg.SeeAdRequest.adID', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=66,
)


_SEEADRESPONSE = _descriptor.Descriptor(
  name='SeeAdResponse',
  full_name='gameMsg.SeeAdResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nPrompt', full_name='gameMsg.SeeAdResponse.nPrompt', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['SeeAdRequest'] = _SEEADREQUEST
DESCRIPTOR.message_types_by_name['SeeAdResponse'] = _SEEADRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SeeAdRequest = _reflection.GeneratedProtocolMessageType('SeeAdRequest', (_message.Message,), dict(
  DESCRIPTOR = _SEEADREQUEST,
  __module__ = 'see_ad_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.SeeAdRequest)
  ))
_sym_db.RegisterMessage(SeeAdRequest)

SeeAdResponse = _reflection.GeneratedProtocolMessageType('SeeAdResponse', (_message.Message,), dict(
  DESCRIPTOR = _SEEADRESPONSE,
  __module__ = 'see_ad_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.SeeAdResponse)
  ))
_sym_db.RegisterMessage(SeeAdResponse)


# @@protoc_insertion_point(module_scope)
