# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: start_game.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='start_game.proto',
  package='gameMsg',
  syntax='proto2',
  serialized_pb=_b('\n\x10start_game.proto\x12\x07gameMsg\"0\n\x10StartGameRequest\x12\x0b\n\x03sID\x18\x01 \x02(\t\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\"\x13\n\x11StartGameResponse\"0\n\x0fStartGameNotify\x12\x0f\n\x07sRoomID\x18\x01 \x02(\t\x12\x0c\n\x04nGID\x18\x02 \x02(\x05\"1\n\x0fTimerGameNotify\x12\x0f\n\x07sRoomID\x18\x01 \x02(\t\x12\r\n\x05nTime\x18\x02 \x02(\x05\"0\n\x10MatchGameRequest\x12\x0b\n\x03sID\x18\x01 \x02(\t\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\"\x13\n\x11MatchGameResponse')
)




_STARTGAMEREQUEST = _descriptor.Descriptor(
  name='StartGameRequest',
  full_name='gameMsg.StartGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sID', full_name='gameMsg.StartGameRequest.sID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='gameMsg.StartGameRequest.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=77,
)


_STARTGAMERESPONSE = _descriptor.Descriptor(
  name='StartGameResponse',
  full_name='gameMsg.StartGameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=98,
)


_STARTGAMENOTIFY = _descriptor.Descriptor(
  name='StartGameNotify',
  full_name='gameMsg.StartGameNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='gameMsg.StartGameNotify.sRoomID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nGID', full_name='gameMsg.StartGameNotify.nGID', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=148,
)


_TIMERGAMENOTIFY = _descriptor.Descriptor(
  name='TimerGameNotify',
  full_name='gameMsg.TimerGameNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='gameMsg.TimerGameNotify.sRoomID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nTime', full_name='gameMsg.TimerGameNotify.nTime', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=199,
)


_MATCHGAMEREQUEST = _descriptor.Descriptor(
  name='MatchGameRequest',
  full_name='gameMsg.MatchGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sID', full_name='gameMsg.MatchGameRequest.sID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='gameMsg.MatchGameRequest.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=249,
)


_MATCHGAMERESPONSE = _descriptor.Descriptor(
  name='MatchGameResponse',
  full_name='gameMsg.MatchGameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=270,
)

DESCRIPTOR.message_types_by_name['StartGameRequest'] = _STARTGAMEREQUEST
DESCRIPTOR.message_types_by_name['StartGameResponse'] = _STARTGAMERESPONSE
DESCRIPTOR.message_types_by_name['StartGameNotify'] = _STARTGAMENOTIFY
DESCRIPTOR.message_types_by_name['TimerGameNotify'] = _TIMERGAMENOTIFY
DESCRIPTOR.message_types_by_name['MatchGameRequest'] = _MATCHGAMEREQUEST
DESCRIPTOR.message_types_by_name['MatchGameResponse'] = _MATCHGAMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartGameRequest = _reflection.GeneratedProtocolMessageType('StartGameRequest', (_message.Message,), dict(
  DESCRIPTOR = _STARTGAMEREQUEST,
  __module__ = 'start_game_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.StartGameRequest)
  ))
_sym_db.RegisterMessage(StartGameRequest)

StartGameResponse = _reflection.GeneratedProtocolMessageType('StartGameResponse', (_message.Message,), dict(
  DESCRIPTOR = _STARTGAMERESPONSE,
  __module__ = 'start_game_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.StartGameResponse)
  ))
_sym_db.RegisterMessage(StartGameResponse)

StartGameNotify = _reflection.GeneratedProtocolMessageType('StartGameNotify', (_message.Message,), dict(
  DESCRIPTOR = _STARTGAMENOTIFY,
  __module__ = 'start_game_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.StartGameNotify)
  ))
_sym_db.RegisterMessage(StartGameNotify)

TimerGameNotify = _reflection.GeneratedProtocolMessageType('TimerGameNotify', (_message.Message,), dict(
  DESCRIPTOR = _TIMERGAMENOTIFY,
  __module__ = 'start_game_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.TimerGameNotify)
  ))
_sym_db.RegisterMessage(TimerGameNotify)

MatchGameRequest = _reflection.GeneratedProtocolMessageType('MatchGameRequest', (_message.Message,), dict(
  DESCRIPTOR = _MATCHGAMEREQUEST,
  __module__ = 'start_game_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.MatchGameRequest)
  ))
_sym_db.RegisterMessage(MatchGameRequest)

MatchGameResponse = _reflection.GeneratedProtocolMessageType('MatchGameResponse', (_message.Message,), dict(
  DESCRIPTOR = _MATCHGAMERESPONSE,
  __module__ = 'start_game_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.MatchGameResponse)
  ))
_sym_db.RegisterMessage(MatchGameResponse)


# @@protoc_insertion_point(module_scope)
