# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: use_tool.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='use_tool.proto',
  package='gameMsg',
  syntax='proto2',
  serialized_pb=_b('\n\x0euse_tool.proto\x12\x07gameMsg\"L\n\x0eUseToolRequest\x12\x0b\n\x03sID\x18\x01 \x02(\t\x12\x0e\n\x06goodID\x18\x02 \x02(\t\x12\x0f\n\x07sRoomID\x18\x03 \x02(\t\x12\x0c\n\x04sDID\x18\x04 \x02(\t\"\x11\n\x0fUseToolResponse\":\n\rUseToolNotify\x12\x0b\n\x03sID\x18\x01 \x02(\t\x12\x0e\n\x06goodID\x18\x02 \x02(\t\x12\x0c\n\x04sDID\x18\x03 \x02(\t')
)




_USETOOLREQUEST = _descriptor.Descriptor(
  name='UseToolRequest',
  full_name='gameMsg.UseToolRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sID', full_name='gameMsg.UseToolRequest.sID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='goodID', full_name='gameMsg.UseToolRequest.goodID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='gameMsg.UseToolRequest.sRoomID', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sDID', full_name='gameMsg.UseToolRequest.sDID', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=103,
)


_USETOOLRESPONSE = _descriptor.Descriptor(
  name='UseToolResponse',
  full_name='gameMsg.UseToolResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=122,
)


_USETOOLNOTIFY = _descriptor.Descriptor(
  name='UseToolNotify',
  full_name='gameMsg.UseToolNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sID', full_name='gameMsg.UseToolNotify.sID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='goodID', full_name='gameMsg.UseToolNotify.goodID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sDID', full_name='gameMsg.UseToolNotify.sDID', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=182,
)

DESCRIPTOR.message_types_by_name['UseToolRequest'] = _USETOOLREQUEST
DESCRIPTOR.message_types_by_name['UseToolResponse'] = _USETOOLRESPONSE
DESCRIPTOR.message_types_by_name['UseToolNotify'] = _USETOOLNOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UseToolRequest = _reflection.GeneratedProtocolMessageType('UseToolRequest', (_message.Message,), dict(
  DESCRIPTOR = _USETOOLREQUEST,
  __module__ = 'use_tool_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.UseToolRequest)
  ))
_sym_db.RegisterMessage(UseToolRequest)

UseToolResponse = _reflection.GeneratedProtocolMessageType('UseToolResponse', (_message.Message,), dict(
  DESCRIPTOR = _USETOOLRESPONSE,
  __module__ = 'use_tool_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.UseToolResponse)
  ))
_sym_db.RegisterMessage(UseToolResponse)

UseToolNotify = _reflection.GeneratedProtocolMessageType('UseToolNotify', (_message.Message,), dict(
  DESCRIPTOR = _USETOOLNOTIFY,
  __module__ = 'use_tool_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.UseToolNotify)
  ))
_sym_db.RegisterMessage(UseToolNotify)


# @@protoc_insertion_point(module_scope)
