# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: use_prompt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='use_prompt.proto',
  package='gameMsg',
  syntax='proto2',
  serialized_pb=_b('\n\x10use_prompt.proto\x12\x07gameMsg\"\x1f\n\x10UsePromptRequest\x12\x0b\n\x03sID\x18\x01 \x02(\t\"\"\n\x11UsePromptResponse\x12\r\n\x05nGold\x18\x01 \x01(\x05')
)




_USEPROMPTREQUEST = _descriptor.Descriptor(
  name='UsePromptRequest',
  full_name='gameMsg.UsePromptRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sID', full_name='gameMsg.UsePromptRequest.sID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=60,
)


_USEPROMPTRESPONSE = _descriptor.Descriptor(
  name='UsePromptResponse',
  full_name='gameMsg.UsePromptResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nGold', full_name='gameMsg.UsePromptResponse.nGold', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['UsePromptRequest'] = _USEPROMPTREQUEST
DESCRIPTOR.message_types_by_name['UsePromptResponse'] = _USEPROMPTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UsePromptRequest = _reflection.GeneratedProtocolMessageType('UsePromptRequest', (_message.Message,), dict(
  DESCRIPTOR = _USEPROMPTREQUEST,
  __module__ = 'use_prompt_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.UsePromptRequest)
  ))
_sym_db.RegisterMessage(UsePromptRequest)

UsePromptResponse = _reflection.GeneratedProtocolMessageType('UsePromptResponse', (_message.Message,), dict(
  DESCRIPTOR = _USEPROMPTRESPONSE,
  __module__ = 'use_prompt_pb2'
  # @@protoc_insertion_point(class_scope:gameMsg.UsePromptResponse)
  ))
_sym_db.RegisterMessage(UsePromptResponse)


# @@protoc_insertion_point(module_scope)
